[package]
name = "sattlec"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "Compiler for the sattle SAT DSL"
default-run = "sattlec"

[[bin]]
name = "sattlec"
path = "src/main.rs"

[dependencies]
clap = { version = "4", features = ["derive"] }
inkwell = { version = "0.10", features = ["llvm22-1"] }
logos = "0.15"

